### ISSUE TITLE
BUG: No waiting the loop

### ISSUE THREAD

**Issue by adoyle-h** [owenthereal/action-upterm#1]
![CleanShot 2024-05-27 at 15 15 18@2x](https://github.com/owenthereal/action-upterm/assets/1998490/625d6998-129d-4243-88d9-e1b2f137cbe5)

```
name: Debug the github action

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup upterm session
        uses: owenthereal/action-upterm@main
        with:
          limit-access-to-actor: true
          limit-access-to-users: adoyle-h
```

**Comment by owenthereal** [comment]
Thanks for reporting. There is a timing issue when waiting for the upterm session to be ready. I fixed it here: https://github.com/owenthereal/action-upterm/commit/ebf2c810043a94ce9b91f310c9f6659e2906b591. Let me know if that addresses your problem.
